<script type="text/javascript" language="javascript" class="init">
var listClientes;
$(document).ready(function() {
        //$('#clientes').DataTable();			
        //$('.edit').hide();
        var texto = $('#listClientes').val();
        listClientes = texto.split(";");
         $("#cliente").autocomplete({
                    source:[listClientes]
                  });
} );
<?php echo $this->view->js;?>

	
</script>

<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>